USE [presama]
GO
/****** Object:  StoredProcedure [dbo].[SP_CABECERA_RECOMPOSICION]    Script Date: 12/10/2017 16:19:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_CABECERA_RECOMPOSICION]
(	
	@IN_OPCION VARCHAR(30),
	@IN_FECHA_INI DATE,
	@IN_FECHA_FIN DATE,
	@IN_VIGENCIA INT,
	@IN_FUERZA VARCHAR(100),
	@IN_MODALIDAD VARCHAR(30)
)
AS 	
	SET NOCOUNT ON

	IF(ISNULL(OBJECT_ID('tempdb..##TablaCabeceraRecom'), 0) <> 0)	
		BEGIN
			DROP TABLE ##TablaCabeceraRecom;
		END

	-- CREA LA TABLA TEMPORAL DONDE ALMACENO LOS DATOS DE LA CABECERA A MOSTRAR
	CREATE TABLE ##TablaCabeceraRecom(
		EMPRESA VARCHAR(50),
		NOMBRE_REPORTE VARCHAR(150),
		REPRESENTANTE VARCHAR(100),
		NIT VARCHAR(30),
		VIGENCIA INT,
		FECHA_HOY DATE,
		FECHA_INI DATE,
		FECHA_FIN DATE,
		FUERZA VARCHAR(100),
		MODALIDAD VARCHAR(30)
	)	

	DECLARE @POSICION int;
	DECLARE @V_CONTADOR INT;
	DECLARE @VEMPRESA VARCHAR(50);
	DECLARE @VNOM_REPORTE VARCHAR(150);
	DECLARE @VREPRESENTANTE VARCHAR(100);
	DECLARE @VNIT VARCHAR(30);
	DECLARE @VFUERZA VARCHAR(100);
	DECLARE @VFUERZA2 VARCHAR(100);
	DECLARE @VMODALIDAD VARCHAR(30);	
	DECLARE @VFECHA_ACTUAL DATE;
	
	SET @VFUERZA2 = @IN_FUERZA;
	SET @VNIT = '900.806.124-1';
	SET @VREPRESENTANTE = 'FABIO ALBERTO VALENCIA BUSTAMA';
	
	--ALMACENO LA FECHA DEL SISTEMA
	SELECT @VFECHA_ACTUAL = CONVERT(date, SYSDATETIME());	

	--ALMACENO EL NOMBRE DE LA EMPRESA
	SELECT @VEMPRESA = EMPCOD
	FROM AUDI_ESM_PRESUP
	WHERE NU_AUTO_ESM = '1';	
	
	IF (@IN_MODALIDAD IS NULL)	
		SET @VMODALIDAD = 0;
	ELSE
		BEGIN
			SELECT @VMODALIDAD = NOMBRE_MODALIDAD
			FROM AUDI_MODALIDAD
			WHERE CODIGO_MODALIDAD = @IN_MODALIDAD;		
		END
	--TERMINA LA CONDICION
	
	SET @IN_FUERZA = @IN_FUERZA + ','
	SET @V_CONTADOR = 0;
	
	--CICLO DONDE CONTROLO SI LA VARIABLE FUERZA VIENE CON TODAS LAS FUERZAS
	WHILE patindex('%,%' , @IN_FUERZA) <> 0
		BEGIN
			--patindex busca un patron en una cadena y nos devuelve su posicion		
			SELECT @POSICION =  patindex('%,%' , @IN_FUERZA)		
			
			--Buscamos la posicion de la primera ,
			SELECT @VFUERZA = left(@IN_FUERZA, @POSICION - 1)				

			--Reemplazamos lo procesado con nada con la funcion stuff
			SELECT @IN_FUERZA = stuff(@IN_FUERZA, 1, @POSICION, '')				
			
			SET @V_CONTADOR = @V_CONTADOR + 1
		END		
	--TERMINA EL CICLO WHILE


	IF (@V_CONTADOR = 0)
		BEGIN
			--SI LA VARIABLE FUERZA VIENE NULL
			SET @VFUERZA = 0
		END
	ELSE	
		IF (@V_CONTADOR = 1)
			--SI LA VARIABLE FUERZA VIENE CON UN CODIGO	
			BEGIN
				SELECT @VFUERZA = NOMBRE_FUERZA
				FROM AUDI_FUERZA_PRESUP
				WHERE CODIGO_FUERZA = @VFUERZA2;			
			END
		ELSE
			--SI LA VARIABLE FUERZA VIENEN CON TODOS LOS CODIGOS
			BEGIN
				SET @VFUERZA = 'FUERZA AEREA - ARMADA NACIONAL - EJERCITO NACIONAL';
			END
	--TERMINA LA CONDICION		
		
	IF (@IN_OPCION = 'OPCION1') 
		-- Recomposicion de presupuesto
		BEGIN
			SET @VNOM_REPORTE = 'INFORME DE RECOMPOSICI&Oacute;N PRESUPUESTAL  CONTRATO 060 DGSM - Droservicio LTDA';
		END
	ELSE	
		IF (@IN_OPCION = 'OPCION2') 
			--Reporte consolidado vigencia
			BEGIN
				SET @VNOM_REPORTE = 'INFORME DE EJECUCI&Oacute;N PRESUPUESTAL CONTRATO 060 DGSM - Droservicio LTDA';
			END
		ELSE 
			IF (@IN_OPCION = 'OPCION3')  
				--Reporte presupuesto anticipo
				BEGIN
					SET @VNOM_REPORTE = 'INFORME DE AMORTIZACI&Oacute;N AL ANTICIPO CONTRATO 060 DGSM - Droservicio LTDA';
				END
			ELSE	
				IF (@IN_OPCION = 'OPCION4') 
					--Reporte presupuesto filtro mes
					BEGIN
						SET @VNOM_REPORTE = 'INFORME DE EJECUCI&Oacute;N PRESUPUESTAL CONTRATO 060 DGSM - Droservicio LTDA';	
					END
	--TERMINA LA CONDICION
	
	--LA TABLA REMPORAL ALMACENA LOS DATOS REQUERIDOS PARA MOSTRAR EN LA CABECERA
	INSERT INTO ##TablaCabeceraRecom(EMPRESA, NOMBRE_REPORTE, REPRESENTANTE, NIT, VIGENCIA, FECHA_HOY, FECHA_INI, FECHA_FIN,FUERZA,MODALIDAD)
	VALUES (@VEMPRESA,@VNOM_REPORTE,@VREPRESENTANTE,@VNIT,@IN_VIGENCIA,@VFECHA_ACTUAL,@IN_FECHA_INI,@IN_FECHA_FIN,@VFUERZA,@VMODALIDAD);
	
	--ENVIO LOS DATOS DE LA TABLA TEMPORAL
	SELECT * 
	FROM ##TablaCabeceraRecom;