USE [presama]
GO
/****** Object:  StoredProcedure [dbo].[SP_FUERZA]    Script Date: 12/10/2017 16:24:15 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_FUERZA]

AS
	SET NOCOUNT ON

	SELECT A.CODIGO_FUERZA COD_FUERZA, A.NOMBRE_FUERZA NOM_FUERZA 
	FROM AUDI_FUERZA_PRESUP A;	