USE [presama]
GO
/****** Object:  StoredProcedure [dbo].[SP_MODALIDAD]    Script Date: 12/10/2017 16:31:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_MODALIDAD]

AS
	SET NOCOUNT ON

	SELECT M.CODIGO_MODALIDAD COD_MODALIDAD, M.NOMBRE_MODALIDAD NOM_MODALIDAD
	FROM AUDI_MODALIDAD M