USE [presama]
GO
/****** Object:  StoredProcedure [dbo].[SP_REPORTESFULL]    Script Date: 12/10/2017 17:03:05 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_REPORTESFULL]
(
	@IN_CODIGO_OPN VARCHAR(10),
	@IN_FECHA_INI DATE,
	@IN_FECHA_FIN DATE
)
AS
	EXEC SP_REPORTE3 @IN_CODIGO_OPN = @IN_CODIGO_OPN, @IN_FECHA_INI = @IN_FECHA_INI , @IN_FECHA_FIN = @IN_FECHA_FIN 
	EXEC SP_REPORTE2 @IN_CODIGO_OPN = @IN_CODIGO_OPN, @IN_FECHA_INI = @IN_FECHA_INI , @IN_FECHA_FIN = @IN_FECHA_FIN 
