USE [presama]
GO
/****** Object:  StoredProcedure [dbo].[SP_VIGENCIA]    Script Date: 12/10/2017 17:03:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[SP_VIGENCIA]

AS
	SET NOCOUNT ON	

	SELECT DISTINCT(VIGENCIA) ANIO_VIGENCIA
	FROM AUDI_ESM_PRESUP;	